Adding moretest, and  log for standar ouput

diff --git a/test/argument b/test/argument
--- a/test/argument
+++ b/test/argument
@@ -1,4 +1,17 @@
 echo bonjour
-echo \"bonjour\"
+echo "bonjour"
 echo 'bonjour'
-echo -n -n One\"argument\"'lo'l; echo \"n\"''ee\"d\"more'?'''\"'\";
+echo $?
+echo $HOME
+echo "$HOME"
+echo $RIP;
+echo $HOME;
+echo $
+echo "$"
+echo \$
+echo "\$"
+echo $\'PWD\'
+echo $\"PWD\"
+echo -n -n One"argument"'lo'l; echo "n"''ee"d"more'?'''"'";
+echo \n\e\e\e\d \m\o\r\e \! \\\\\\
+echo '\\please\\' "\"fail\\"
